/// Flutter icons ExIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ExIcons
///      fonts:
///       - asset: fonts/ExIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class ExIcons {
  ExIcons._();

  static const _kFontFam = 'ExIcons';

  static const IconData fi_rr_add =
      IconData(0xe800, fontFamily: _kFontFam);
  static const IconData fi_rr_alarm_clock =
      IconData(0xe801, fontFamily: _kFontFam);
  static const IconData fi_rr_align_center =
      IconData(0xe802, fontFamily: _kFontFam);
  static const IconData fi_rr_align_justify =
      IconData(0xe803, fontFamily: _kFontFam);
  static const IconData fi_rr_align_left =
      IconData(0xe804, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_double_left =
      IconData(0xe805, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_double_right =
      IconData(0xe806, fontFamily: _kFontFam);
  static const IconData fi_rr_align_right =
      IconData(0xe807, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_double_small_left =
      IconData(0xe808, fontFamily: _kFontFam);
  static const IconData fi_rr_ambulance =
      IconData(0xe809, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_double_small_right =
      IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_down =
      IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_left =
      IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_right =
      IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_small_left =
      IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_small_right =
      IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_small_up =
      IconData(0xe810, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_up =
      IconData(0xe811, fontFamily: _kFontFam);
  static const IconData fi_rr_apps_delete =
      IconData(0xe812, fontFamily: _kFontFam);
  static const IconData fi_rr_apps =
      IconData(0xe813, fontFamily: _kFontFam);
  static const IconData fi_rr_archive =
      IconData(0xe814, fontFamily: _kFontFam);
  static const IconData fi_rr_angle_small_down =
      IconData(0xe815, fontFamily: _kFontFam);
  static const IconData fi_rr_apps_sort =
      IconData(0xe816, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_down =
      IconData(0xe817, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_left =
      IconData(0xe818, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_right =
      IconData(0xe819, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_small_down =
      IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_small_left =
      IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData fi_rr_apps_add =
      IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_small_right =
      IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_small_up =
      IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData fi_rr_arrow_up =
      IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData fi_rr_backpack =
      IconData(0xe820, fontFamily: _kFontFam);
  static const IconData fi_rr_badge =
      IconData(0xe821, fontFamily: _kFontFam);
  static const IconData fi_rr_barber_shop =
      IconData(0xe822, fontFamily: _kFontFam);
  static const IconData fi_rr_baseball =
      IconData(0xe823, fontFamily: _kFontFam);
  static const IconData fi_rr_bell_school =
      IconData(0xe824, fontFamily: _kFontFam);
  static const IconData fi_rr_billiard =
      IconData(0xe825, fontFamily: _kFontFam);
  static const IconData fi_rr_ban =
      IconData(0xe826, fontFamily: _kFontFam);
  static const IconData fi_rr_asterisk =
      IconData(0xe827, fontFamily: _kFontFam);
  static const IconData fi_rr_band_aid =
      IconData(0xe828, fontFamily: _kFontFam);
  static const IconData fi_rr_bank =
      IconData(0xe829, fontFamily: _kFontFam);
  static const IconData fi_rr_basketball =
      IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData fi_rr_book_alt =
      IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData fi_rr_box_alt =
      IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData fi_rr_bowling =
      IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData fi_rr_bell_ring =
      IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData fi_rr_bell =
      IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData fi_rr_bold =
      IconData(0xe830, fontFamily: _kFontFam);
  static const IconData fi_rr_box =
      IconData(0xe831, fontFamily: _kFontFam);
  static const IconData fi_rr_briefcase =
      IconData(0xe832, fontFamily: _kFontFam);
  static const IconData fi_rr_bookmark =
      IconData(0xe833, fontFamily: _kFontFam);
  static const IconData fi_rr_book =
      IconData(0xe834, fontFamily: _kFontFam);
  static const IconData fi_rr_broom =
      IconData(0xe835, fontFamily: _kFontFam);
  static const IconData fi_rr_browser =
      IconData(0xe836, fontFamily: _kFontFam);
  static const IconData fi_rr_bug =
      IconData(0xe837, fontFamily: _kFontFam);
  static const IconData fi_rr_building =
      IconData(0xe838, fontFamily: _kFontFam);
  static const IconData fi_rr_bulb =
      IconData(0xe839, fontFamily: _kFontFam);
  static const IconData fi_rr_calculator =
      IconData(0xe83a, fontFamily: _kFontFam);
  static const IconData fi_rr_brush =
      IconData(0xe83b, fontFamily: _kFontFam);
  static const IconData fi_rr_calendar =
      IconData(0xe83c, fontFamily: _kFontFam);
  static const IconData fi_rr_camera =
      IconData(0xe83d, fontFamily: _kFontFam);
  static const IconData fi_rr_caret_down =
      IconData(0xe83e, fontFamily: _kFontFam);
  static const IconData fi_rr_caret_left =
      IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData fi_rr_caret_right =
      IconData(0xe840, fontFamily: _kFontFam);
  static const IconData fi_rr_caret_up =
      IconData(0xe841, fontFamily: _kFontFam);
  static const IconData fi_rr_check =
      IconData(0xe842, fontFamily: _kFontFam);
  static const IconData fi_rr_checkbox =
      IconData(0xe843, fontFamily: _kFontFam);
  static const IconData fi_rr_chess =
      IconData(0xe844, fontFamily: _kFontFam);
  static const IconData fi_rr_circle_small =
      IconData(0xe845, fontFamily: _kFontFam);
  static const IconData fi_rr_circle =
      IconData(0xe846, fontFamily: _kFontFam);
  static const IconData fi_rr_clip =
      IconData(0xe847, fontFamily: _kFontFam);
  static const IconData fi_rr_clock =
      IconData(0xe848, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud_check =
      IconData(0xe849, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud_disabled =
      IconData(0xe84a, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud_download =
      IconData(0xe84b, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud_share =
      IconData(0xe84c, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud_upload =
      IconData(0xe84d, fontFamily: _kFontFam);
  static const IconData fi_rr_cloud =
      IconData(0xe84e, fontFamily: _kFontFam);
  static const IconData fi_rr_comment_alt =
      IconData(0xe84f, fontFamily: _kFontFam);
  static const IconData fi_rr_comment =
      IconData(0xe850, fontFamily: _kFontFam);
  static const IconData fi_rr_compress_alt =
      IconData(0xe851, fontFamily: _kFontFam);
  static const IconData fi_rr_compress =
      IconData(0xe852, fontFamily: _kFontFam);
  static const IconData fi_rr_computer =
      IconData(0xe853, fontFamily: _kFontFam);
  static const IconData fi_rr_cookie =
      IconData(0xe854, fontFamily: _kFontFam);
  static const IconData fi_rr_copy_alt =
      IconData(0xe855, fontFamily: _kFontFam);
  static const IconData fi_rr_copy =
      IconData(0xe856, fontFamily: _kFontFam);
  static const IconData fi_rr_copyright =
      IconData(0xe857, fontFamily: _kFontFam);
  static const IconData fi_rr_cream =
      IconData(0xe858, fontFamily: _kFontFam);
  static const IconData fi_rr_credit_card =
      IconData(0xe859, fontFamily: _kFontFam);
  static const IconData fi_rr_cross_circle =
      IconData(0xe85a, fontFamily: _kFontFam);
  static const IconData fi_rr_cross_small =
      IconData(0xe85b, fontFamily: _kFontFam);
  static const IconData fi_rr_cross =
      IconData(0xe85c, fontFamily: _kFontFam);
  static const IconData fi_rr_crown =
      IconData(0xe85d, fontFamily: _kFontFam);
  static const IconData fi_rr_cursor_finger =
      IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData fi_rr_cursor_plus =
      IconData(0xe85f, fontFamily: _kFontFam);
  static const IconData fi_rr_cursor_text_alt =
      IconData(0xe860, fontFamily: _kFontFam);
  static const IconData fi_rr_cursor_text =
      IconData(0xe861, fontFamily: _kFontFam);
  static const IconData fi_rr_cursor =
      IconData(0xe862, fontFamily: _kFontFam);
  static const IconData fi_rr_dart =
      IconData(0xe863, fontFamily: _kFontFam);
  static const IconData fi_rr_dashboard =
      IconData(0xe864, fontFamily: _kFontFam);
  static const IconData fi_rr_data_transfer =
      IconData(0xe865, fontFamily: _kFontFam);
  static const IconData fi_rr_database =
      IconData(0xe866, fontFamily: _kFontFam);
  static const IconData fi_rr_delete =
      IconData(0xe867, fontFamily: _kFontFam);
  static const IconData fi_rr_diamond =
      IconData(0xe868, fontFamily: _kFontFam);
  static const IconData fi_rr_dice =
      IconData(0xe869, fontFamily: _kFontFam);
  static const IconData fi_rr_diploma =
      IconData(0xe86a, fontFamily: _kFontFam);
  static const IconData fi_rr_disk =
      IconData(0xe86b, fontFamily: _kFontFam);
  static const IconData fi_rr_doctor =
      IconData(0xe86c, fontFamily: _kFontFam);
  static const IconData fi_rr_document_signed =
      IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData fi_rr_dollar =
      IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData fi_rr_document =
      IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData fi_rr_download =
      IconData(0xe870, fontFamily: _kFontFam);
  static const IconData fi_rr_duplicate =
      IconData(0xe871, fontFamily: _kFontFam);
  static const IconData fi_rr_e_learning =
      IconData(0xe872, fontFamily: _kFontFam);
  static const IconData fi_rr_earnings =
      IconData(0xe873, fontFamily: _kFontFam);
  static const IconData fi_rr_edit_alt =
      IconData(0xe874, fontFamily: _kFontFam);
  static const IconData fi_rr_edit =
      IconData(0xe875, fontFamily: _kFontFam);
  static const IconData fi_rr_envelope =
      IconData(0xe876, fontFamily: _kFontFam);
  static const IconData fi_rr_euro =
      IconData(0xe877, fontFamily: _kFontFam);
  static const IconData fi_rr_exclamation =
      IconData(0xe878, fontFamily: _kFontFam);
  static const IconData fi_rr_expand =
      IconData(0xe879, fontFamily: _kFontFam);
  static const IconData fi_rr_eye_crossed =
      IconData(0xe87a, fontFamily: _kFontFam);
  static const IconData fi_rr_eye =
      IconData(0xe87b, fontFamily: _kFontFam);
  static const IconData fi_rr_eye_dropper =
      IconData(0xe87c, fontFamily: _kFontFam);
  static const IconData fi_rr_feather =
      IconData(0xe87d, fontFamily: _kFontFam);
  static const IconData fi_rr_file_add =
      IconData(0xe87e, fontFamily: _kFontFam);
  static const IconData fi_rr_file_ai =
      IconData(0xe87f, fontFamily: _kFontFam);
  static const IconData fi_rr_file_check =
      IconData(0xe880, fontFamily: _kFontFam);
  static const IconData fi_rr_file_delete =
      IconData(0xe881, fontFamily: _kFontFam);
  static const IconData fi_rr_file_eps =
      IconData(0xe882, fontFamily: _kFontFam);
  static const IconData fi_rr_file_gif =
      IconData(0xe883, fontFamily: _kFontFam);
  static const IconData fi_rr_file_music =
      IconData(0xe884, fontFamily: _kFontFam);
  static const IconData fi_rr_file_psd =
      IconData(0xe885, fontFamily: _kFontFam);
  static const IconData fi_rr_file =
      IconData(0xe886, fontFamily: _kFontFam);
  static const IconData fi_rr_fill =
      IconData(0xe887, fontFamily: _kFontFam);
  static const IconData fi_rr_film =
      IconData(0xe888, fontFamily: _kFontFam);
  static const IconData fi_rr_filter =
      IconData(0xe889, fontFamily: _kFontFam);
  static const IconData fi_rr_fingerprint =
      IconData(0xe88a, fontFamily: _kFontFam);
  static const IconData fi_rr_flag =
      IconData(0xe88b, fontFamily: _kFontFam);
  static const IconData fi_rr_flame =
      IconData(0xe88c, fontFamily: _kFontFam);
  static const IconData fi_rr_flip_horizontal =
      IconData(0xe88d, fontFamily: _kFontFam);
  static const IconData fi_rr_folder_add =
      IconData(0xe88e, fontFamily: _kFontFam);
  static const IconData fi_rr_folder =
      IconData(0xe88f, fontFamily: _kFontFam);
  static const IconData fi_rr_following =
      IconData(0xe890, fontFamily: _kFontFam);
  static const IconData fi_rr_football =
      IconData(0xe891, fontFamily: _kFontFam);
  static const IconData fi_rr_form =
      IconData(0xe892, fontFamily: _kFontFam);
  static const IconData fi_rr_forward =
      IconData(0xe893, fontFamily: _kFontFam);
  static const IconData fi_rr_ftp =
      IconData(0xe894, fontFamily: _kFontFam);
  static const IconData fi_rr_gallery =
      IconData(0xe895, fontFamily: _kFontFam);
  static const IconData fi_rr_glasses =
      IconData(0xe896, fontFamily: _kFontFam);
  static const IconData fi_rr_globe_alt =
      IconData(0xe897, fontFamily: _kFontFam);
  static const IconData fi_rr_globe =
      IconData(0xe898, fontFamily: _kFontFam);
  static const IconData fi_rr_golf =
      IconData(0xe899, fontFamily: _kFontFam);
  static const IconData fi_rr_graduation_cap =
      IconData(0xe89a, fontFamily: _kFontFam);
  static const IconData fi_rr_graphic_tablet =
      IconData(0xe89b, fontFamily: _kFontFam);
  static const IconData fi_rr_grid_alt =
      IconData(0xe89c, fontFamily: _kFontFam);
  static const IconData fi_rr_grid =
      IconData(0xe89d, fontFamily: _kFontFam);
  static const IconData fi_rr_gym =
      IconData(0xe89e, fontFamily: _kFontFam);
  static const IconData fi_rr_headphones =
      IconData(0xe89f, fontFamily: _kFontFam);
  static const IconData fi_rr_headset =
      IconData(0xe8a0, fontFamily: _kFontFam);
  static const IconData fi_rr_heart =
      IconData(0xe8a1, fontFamily: _kFontFam);
  static const IconData fi_rr_home =
      IconData(0xe8a2, fontFamily: _kFontFam);
  static const IconData fi_rr_hourglass_end =
      IconData(0xe8a3, fontFamily: _kFontFam);
  static const IconData fi_rr_hourglass =
      IconData(0xe8a4, fontFamily: _kFontFam);
  static const IconData fi_rr_ice_skate =
      IconData(0xe8a5, fontFamily: _kFontFam);
  static const IconData fi_rr_id_badge =
      IconData(0xe8a6, fontFamily: _kFontFam);
  static const IconData fi_rr_inbox =
      IconData(0xe8a7, fontFamily: _kFontFam);
  static const IconData fi_rr_incognito =
      IconData(0xe8a8, fontFamily: _kFontFam);
  static const IconData fi_rr_indent =
      IconData(0xe8a9, fontFamily: _kFontFam);
  static const IconData fi_rr_infinity =
      IconData(0xe8aa, fontFamily: _kFontFam);
  static const IconData fi_rr_info =
      IconData(0xe8ab, fontFamily: _kFontFam);
  static const IconData fi_rr_interactive =
      IconData(0xe8ac, fontFamily: _kFontFam);
  static const IconData fi_rr_interlining =
      IconData(0xe8ad, fontFamily: _kFontFam);
  static const IconData fi_rr_interrogation =
      IconData(0xe8ae, fontFamily: _kFontFam);
  static const IconData fi_rr_italic =
      IconData(0xe8af, fontFamily: _kFontFam);
  static const IconData fi_rr_jpg =
      IconData(0xe8b0, fontFamily: _kFontFam);
  static const IconData fi_rr_key =
      IconData(0xe8b1, fontFamily: _kFontFam);
  static const IconData fi_rr_keyboard =
      IconData(0xe8b2, fontFamily: _kFontFam);
  static const IconData fi_rr_label =
      IconData(0xe8b3, fontFamily: _kFontFam);
  static const IconData fi_rr_laptop =
      IconData(0xe8b4, fontFamily: _kFontFam);
  static const IconData fi_rr_lasso =
      IconData(0xe8b5, fontFamily: _kFontFam);
  static const IconData fi_rr_layers =
      IconData(0xe8b6, fontFamily: _kFontFam);
  static const IconData fi_rr_layout_fluid =
      IconData(0xe8b7, fontFamily: _kFontFam);
  static const IconData fi_rr_letter_case =
      IconData(0xe8b8, fontFamily: _kFontFam);
  static const IconData fi_rr_life_ring =
      IconData(0xe8b9, fontFamily: _kFontFam);
  static const IconData fi_rr_line_width =
      IconData(0xe8ba, fontFamily: _kFontFam);
  static const IconData fi_rr_link =
      IconData(0xe8bb, fontFamily: _kFontFam);
  static const IconData fi_rr_lipstick =
      IconData(0xe8bc, fontFamily: _kFontFam);
  static const IconData fi_rr_list_check =
      IconData(0xe8bd, fontFamily: _kFontFam);
  static const IconData fi_rr_list =
      IconData(0xe8be, fontFamily: _kFontFam);
  static const IconData fi_rr_location_alt =
      IconData(0xe8bf, fontFamily: _kFontFam);
  static const IconData fi_rr_lock_alt =
      IconData(0xe8c0, fontFamily: _kFontFam);
  static const IconData fi_rr_lock =
      IconData(0xe8c1, fontFamily: _kFontFam);
  static const IconData fi_rr_magic_wand =
      IconData(0xe8c2, fontFamily: _kFontFam);
  static const IconData fi_rr_makeup_brush =
      IconData(0xe8c3, fontFamily: _kFontFam);
  static const IconData fi_rr_marker_time =
      IconData(0xe8c4, fontFamily: _kFontFam);
  static const IconData fi_rr_marker =
      IconData(0xe8c5, fontFamily: _kFontFam);
  static const IconData fi_rr_medicine =
      IconData(0xe8c6, fontFamily: _kFontFam);
  static const IconData fi_rr_megaphone =
      IconData(0xe8c7, fontFamily: _kFontFam);
  static const IconData fi_rr_microphone =
      IconData(0xe8cb, fontFamily: _kFontFam);
  static const IconData fi_rr_mobile =
      IconData(0xe8ce, fontFamily: _kFontFam);
  static const IconData fi_rr_mode_landscape =
      IconData(0xe8cf, fontFamily: _kFontFam);
  static const IconData fi_rr_mode_portrait =
      IconData(0xe8d0, fontFamily: _kFontFam);
  static const IconData fi_rr_money =
      IconData(0xe8d1, fontFamily: _kFontFam);
  static const IconData fi_rr_mouse =
      IconData(0xe8d2, fontFamily: _kFontFam);
  static const IconData fi_rr_music_alt =
      IconData(0xe8d3, fontFamily: _kFontFam);
  static const IconData fi_rr_music =
      IconData(0xe8d4, fontFamily: _kFontFam);
  static const IconData fi_rr_network_cloud =
      IconData(0xe8d5, fontFamily: _kFontFam);
  static const IconData fi_rr_network =
      IconData(0xe8d6, fontFamily: _kFontFam);
  static const IconData fi_rr_notebook =
      IconData(0xe8d7, fontFamily: _kFontFam);
  static const IconData fi_rr_opacity =
      IconData(0xe8d8, fontFamily: _kFontFam);
  static const IconData fi_rr_package =
      IconData(0xe8d9, fontFamily: _kFontFam);
  static const IconData fi_rr_paint_brush =
      IconData(0xe8da, fontFamily: _kFontFam);
  static const IconData fi_rr_palette =
      IconData(0xe8db, fontFamily: _kFontFam);
  static const IconData fi_rr_paper_plane =
      IconData(0xe8dc, fontFamily: _kFontFam);
  static const IconData fi_rr_password =
      IconData(0xe8dd, fontFamily: _kFontFam);
  static const IconData fi_rr_pause =
      IconData(0xe8de, fontFamily: _kFontFam);
  static const IconData fi_rr_pencil =
      IconData(0xe8df, fontFamily: _kFontFam);
  static const IconData fi_rr_pharmacy =
      IconData(0xe8e0, fontFamily: _kFontFam);
  static const IconData fi_rr_physics =
      IconData(0xe8e1, fontFamily: _kFontFam);
  static const IconData fi_rr_picture =
      IconData(0xe8e2, fontFamily: _kFontFam);
  static const IconData fi_rr_ping_pong =
      IconData(0xe8e3, fontFamily: _kFontFam);
  static const IconData fi_rr_play_alt =
      IconData(0xe8e4, fontFamily: _kFontFam);
  static const IconData fi_rr_play =
      IconData(0xe8e5, fontFamily: _kFontFam);
  static const IconData fi_rr_plus_small =
      IconData(0xe8e6, fontFamily: _kFontFam);
  static const IconData fi_rr_playing_cards =
      IconData(0xe8e7, fontFamily: _kFontFam);
  static const IconData fi_rr_plus =
      IconData(0xe8e8, fontFamily: _kFontFam);
  static const IconData fi_rr_poker_chip =
      IconData(0xe8e9, fontFamily: _kFontFam);
  static const IconData fi_rr_portrait =
      IconData(0xe8ea, fontFamily: _kFontFam);
  static const IconData fi_rr_pound =
      IconData(0xe8eb, fontFamily: _kFontFam);
  static const IconData fi_rr_power =
      IconData(0xe8ec, fontFamily: _kFontFam);
  static const IconData fi_rr_presentation =
      IconData(0xe8ed, fontFamily: _kFontFam);
  static const IconData fi_rr_print =
      IconData(0xe8ee, fontFamily: _kFontFam);
  static const IconData fi_rr_protractor =
      IconData(0xe8ef, fontFamily: _kFontFam);
  static const IconData fi_rr_pulse =
      IconData(0xe8f0, fontFamily: _kFontFam);
  static const IconData fi_rr_quote_right =
      IconData(0xe8f1, fontFamily: _kFontFam);
  static const IconData fi_rr_rec =
      IconData(0xe8f2, fontFamily: _kFontFam);
  static const IconData fi_rr_receipt =
      IconData(0xe8f3, fontFamily: _kFontFam);
  static const IconData fi_rr_rectangle_horizontal =
      IconData(0xe8f4, fontFamily: _kFontFam);
  static const IconData fi_rr_rectangle_panoramic =
      IconData(0xe8f5, fontFamily: _kFontFam);
  static const IconData fi_rr_rectangle_vertical =
      IconData(0xe8f6, fontFamily: _kFontFam);
  static const IconData fi_rr_redo =
      IconData(0xe8f7, fontFamily: _kFontFam);
  static const IconData fi_rr_reflect =
      IconData(0xe8f8, fontFamily: _kFontFam);
  static const IconData fi_rr_refresh =
      IconData(0xe8f9, fontFamily: _kFontFam);
  static const IconData fi_rr_resize =
      IconData(0xe8fa, fontFamily: _kFontFam);
  static const IconData fi_rr_resources =
      IconData(0xe8fb, fontFamily: _kFontFam);
  static const IconData fi_rr_rewind =
      IconData(0xe8fc, fontFamily: _kFontFam);
  static const IconData fi_rr_rocket =
      IconData(0xe8fd, fontFamily: _kFontFam);
  static const IconData fi_rr_rotate_right =
      IconData(0xe8fe, fontFamily: _kFontFam);
  static const IconData fi_rr_rugby =
      IconData(0xe8ff, fontFamily: _kFontFam);
  static const IconData fi_rr_scale =
      IconData(0xe900, fontFamily: _kFontFam);
  static const IconData fi_rr_school_bus =
      IconData(0xe901, fontFamily: _kFontFam);
  static const IconData fi_rr_school =
      IconData(0xe902, fontFamily: _kFontFam);
  static const IconData fi_rr_scissors =
      IconData(0xe903, fontFamily: _kFontFam);
  static const IconData fi_rr_screen =
      IconData(0xe904, fontFamily: _kFontFam);
  static const IconData fi_rr_search_alt =
      IconData(0xe905, fontFamily: _kFontFam);
  static const IconData fi_rr_search =
      IconData(0xe906, fontFamily: _kFontFam);
  static const IconData fi_rr_settings_sliders =
      IconData(0xe907, fontFamily: _kFontFam);
  static const IconData fi_rr_settings =
      IconData(0xe908, fontFamily: _kFontFam);
  static const IconData fi_rr_share =
      IconData(0xe909, fontFamily: _kFontFam);
  static const IconData fi_rr_shield_check =
      IconData(0xe90a, fontFamily: _kFontFam);
  static const IconData fi_rr_shield_exclamation =
      IconData(0xe90b, fontFamily: _kFontFam);
  static const IconData fi_rr_shield_interrogation =
      IconData(0xe90c, fontFamily: _kFontFam);
  static const IconData fi_rr_shield_plus =
      IconData(0xe90d, fontFamily: _kFontFam);
  static const IconData fi_rr_shield =
      IconData(0xe90e, fontFamily: _kFontFam);
  static const IconData fi_rr_shop =
      IconData(0xe90f, fontFamily: _kFontFam);
  static const IconData fi_rr_shopping_bag_add =
      IconData(0xe910, fontFamily: _kFontFam);
  static const IconData fi_rr_shopping_bag =
      IconData(0xe911, fontFamily: _kFontFam);
  static const IconData fi_rr_shopping_cart_add =
      IconData(0xe912, fontFamily: _kFontFam);
  static const IconData fi_rr_shopping_cart_check =
      IconData(0xe913, fontFamily: _kFontFam);
  static const IconData fi_rr_shopping_cart =
      IconData(0xe914, fontFamily: _kFontFam);
  static const IconData fi_rr_shuffle =
      IconData(0xe915, fontFamily: _kFontFam);
  static const IconData fi_rr_sign_in =
      IconData(0xe916, fontFamily: _kFontFam);
  static const IconData fi_rr_sign_out =
      IconData(0xe917, fontFamily: _kFontFam);
  static const IconData fi_rr_signal_alt_1 =
      IconData(0xe918, fontFamily: _kFontFam);
  static const IconData fi_rr_signal_alt_2 =
      IconData(0xe919, fontFamily: _kFontFam);
  static const IconData fi_rr_signal_alt =
      IconData(0xe91a, fontFamily: _kFontFam);
  static const IconData fi_rr_skateboard =
      IconData(0xe91b, fontFamily: _kFontFam);
  static const IconData fi_rr_smartphone =
      IconData(0xe91c, fontFamily: _kFontFam);
  static const IconData fi_rr_soap =
      IconData(0xe91d, fontFamily: _kFontFam);
  static const IconData fi_rr_spa =
      IconData(0xe91e, fontFamily: _kFontFam);
  static const IconData fi_rr_speaker =
      IconData(0xe91f, fontFamily: _kFontFam);
  static const IconData fi_rr_spinner_alt =
      IconData(0xe920, fontFamily: _kFontFam);
  static const IconData fi_rr_spinner =
      IconData(0xe921, fontFamily: _kFontFam);
  static const IconData fi_rr_square_root =
      IconData(0xe922, fontFamily: _kFontFam);
  static const IconData fi_rr_square =
      IconData(0xe923, fontFamily: _kFontFam);
  static const IconData fi_rr_star =
      IconData(0xe924, fontFamily: _kFontFam);
  static const IconData fi_rr_stats =
      IconData(0xe925, fontFamily: _kFontFam);
  static const IconData fi_rr_stethoscope =
      IconData(0xe926, fontFamily: _kFontFam);
  static const IconData fi_rr_sticker =
      IconData(0xe927, fontFamily: _kFontFam);
  static const IconData fi_rr_stop =
      IconData(0xe928, fontFamily: _kFontFam);
  static const IconData fi_rr_stopwatch =
      IconData(0xe929, fontFamily: _kFontFam);
  static const IconData fi_rr_subtitles =
      IconData(0xe92a, fontFamily: _kFontFam);
  static const IconData fi_rr_surfing =
      IconData(0xe92b, fontFamily: _kFontFam);
  static const IconData fi_rr_sword =
      IconData(0xe92c, fontFamily: _kFontFam);
  static const IconData fi_rr_syringe =
      IconData(0xe92d, fontFamily: _kFontFam);
  static const IconData fi_rr_tablet =
      IconData(0xe92e, fontFamily: _kFontFam);
  static const IconData fi_rr_target =
      IconData(0xe92f, fontFamily: _kFontFam);
  static const IconData fi_rr_tennis =
      IconData(0xe930, fontFamily: _kFontFam);
  static const IconData fi_rr_test_tube =
      IconData(0xe931, fontFamily: _kFontFam);
  static const IconData fi_rr_test =
      IconData(0xe932, fontFamily: _kFontFam);
  static const IconData fi_rr_text_check =
      IconData(0xe933, fontFamily: _kFontFam);
  static const IconData fi_rr_text =
      IconData(0xe934, fontFamily: _kFontFam);
  static const IconData fi_rr_thumbs_down =
      IconData(0xe935, fontFamily: _kFontFam);
  static const IconData fi_rr_thumbs_up =
      IconData(0xe936, fontFamily: _kFontFam);
  static const IconData fi_rr_ticket =
      IconData(0xe937, fontFamily: _kFontFam);
  static const IconData fi_rr_time_add =
      IconData(0xe938, fontFamily: _kFontFam);
  static const IconData fi_rr_time_check =
      IconData(0xe939, fontFamily: _kFontFam);
  static const IconData fi_rr_time_delete =
      IconData(0xe93a, fontFamily: _kFontFam);
  static const IconData fi_rr_time_fast =
      IconData(0xe93b, fontFamily: _kFontFam);
  static const IconData fi_rr_time_forward_sixty =
      IconData(0xe93c, fontFamily: _kFontFam);
  static const IconData fi_rr_time_forward_ten =
      IconData(0xe93d, fontFamily: _kFontFam);
  static const IconData fi_rr_time_forward =
      IconData(0xe93e, fontFamily: _kFontFam);
  static const IconData fi_rr_time_half_past =
      IconData(0xe93f, fontFamily: _kFontFam);
  static const IconData fi_rr_time_oclock =
      IconData(0xe940, fontFamily: _kFontFam);
  static const IconData fi_rr_time_past =
      IconData(0xe941, fontFamily: _kFontFam);
  static const IconData fi_rr_time_quarter_past =
      IconData(0xe942, fontFamily: _kFontFam);
  static const IconData fi_rr_time_quarter_to =
      IconData(0xe943, fontFamily: _kFontFam);
  static const IconData fi_rr_time_twenty_four =
      IconData(0xe944, fontFamily: _kFontFam);
  static const IconData fi_rr_tool_crop =
      IconData(0xe945, fontFamily: _kFontFam);
  static const IconData fi_rr_tool_marquee =
      IconData(0xe946, fontFamily: _kFontFam);
  static const IconData fi_rr_tooth =
      IconData(0xe947, fontFamily: _kFontFam);
  static const IconData fi_rr_transform =
      IconData(0xe948, fontFamily: _kFontFam);
  static const IconData fi_rr_trash =
      IconData(0xe949, fontFamily: _kFontFam);
  static const IconData fi_rr_treatment =
      IconData(0xe94a, fontFamily: _kFontFam);
  static const IconData fi_rr_trophy =
      IconData(0xe94b, fontFamily: _kFontFam);
  static const IconData fi_rr_umbrella =
      IconData(0xe94c, fontFamily: _kFontFam);
  static const IconData fi_rr_underline =
      IconData(0xe94d, fontFamily: _kFontFam);
  static const IconData fi_rr_undo =
      IconData(0xe94e, fontFamily: _kFontFam);
  static const IconData fi_rr_unlock =
      IconData(0xe94f, fontFamily: _kFontFam);
  static const IconData fi_rr_upload =
      IconData(0xe950, fontFamily: _kFontFam);
  static const IconData fi_rr_usb_drive =
      IconData(0xe951, fontFamily: _kFontFam);
  static const IconData fi_rr_user_add =
      IconData(0xe952, fontFamily: _kFontFam);
  static const IconData fi_rr_user_delete =
      IconData(0xe953, fontFamily: _kFontFam);
  static const IconData fi_rr_user_remove =
      IconData(0xe954, fontFamily: _kFontFam);
  static const IconData fi_rr_user_time =
      IconData(0xe955, fontFamily: _kFontFam);
  static const IconData fi_rr_user =
      IconData(0xe956, fontFamily: _kFontFam);
  static const IconData fi_rr_users =
      IconData(0xe957, fontFamily: _kFontFam);
  static const IconData fi_rr_vector_alt =
      IconData(0xe958, fontFamily: _kFontFam);
  static const IconData fi_rr_vector =
      IconData(0xe959, fontFamily: _kFontFam);
  static const IconData fi_rr_video_camera =
      IconData(0xe95a, fontFamily: _kFontFam);
  static const IconData fi_rr_volleyball =
      IconData(0xe95b, fontFamily: _kFontFam);
  static const IconData fi_rr_volume =
      IconData(0xe95c, fontFamily: _kFontFam);
  static const IconData fi_rr_wifi_alt =
      IconData(0xe95d, fontFamily: _kFontFam);
  static const IconData fi_rr_world =
      IconData(0xe95e, fontFamily: _kFontFam);
  static const IconData fi_rr_yen =
      IconData(0xe95f, fontFamily: _kFontFam);
  static const IconData fi_rr_zoom_in =
      IconData(0xe960, fontFamily: _kFontFam);
  static const IconData fi_rr_zoom_out =
      IconData(0xe961, fontFamily: _kFontFam);
}
